# Generated by Django 3.0.3 on 2020-02-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('0', 'Recomendation'), ('1', 'Internet'), ('2', 'By Chance')], max_length=28, unique=True)),
                ('blacklist', models.BooleanField(default=False)),
                ('authentic', models.CharField(max_length=192, null=True)),
                ('photo', models.ImageField(blank=True, height_field=300, upload_to='images/Customers')),
                ('age', models.IntegerField(default=16)),
                ('angaged', models.DateField(blank=True, default=None, null=True)),
                ('rezume', models.TextField(blank=True, max_length=1024)),
                ('cover', models.FileField(blank=True, upload_to='cover/Customers')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('customer', models.CharField(max_length=48, null=True, unique=True)),
                ('customer_adress', models.CharField(max_length=96, null=True)),
                ('customer_rezume', models.TextField(blank=True, max_length=1024)),
                ('published', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
